# Introduction

Spiritual and religious abuse is a new construct to describe a serious problem. As @KochEdstrom2022 put it:

>The terms “spiritual abuse” and “religious abuse” are used interchangeably by researchers. Oakley et al. (2018) define spiritual abuse as a form of emotional and psychological abuse characterized by systemic patterns of coercion and control in religious contexts; spiritual abuse is distinguished from broad emotional abuse by its common inclusion of specifically religious elements, like the quoting of scripture or the giving of a “divine rationale” for mistreatment. (Much like R/S abuse, there is no consensus definition of emotional abuse, but Pearl (1994) proposed the following categories: rejecting, isolating, terrorizing, ignoring, corrupting, verbally assaulting, and overpressuring.) Swindle (2017) casts a wider net and identifies three broad categories of religious abuse: abuse perpetrated by religious leaders, abuse perpetrated by a religious group or person representing a religious group, and abuse with a religious or spiritual component. Other definitions focus on specific forms of religious or spiritual abuse, like using scripture or religious language to justify domestic abuse (Cares & Cusick, 2012; Warford, 2014), any sexual or physically abusive act done by a clergy member (Doyle, 2006), and theologically sanctioned mistreatment of LGBTQ persons (Foster, Bowland, & Vosler, 2015). Taken together, R/S abuse is distinguished from other types of abuse by a religious component of one sort or another. As conceived for this article, combining the approaches of Oakley, et al. (2018) and Swindle (2017), spiritual abuse is defined as a type of emotional and psychological abuse perpetrated by a religious leader or group and/or with a religious or spiritual component, usually involving coercion or control. It is separable from other types of abuse that may co-ccur or take place in a religious context or by a religious figure, like clergy sexual abuse or domestic violence excused through the quoting of scripture. A survivor of clergy sexual abuse, then, is understood for our purposes to have been abused both sexually and spiritually. The sexual abuse can be expected to have effects on the survivor similar to other instances of sexual abuse, while the spiritual abuse will likely affect whether or how they are able to practice their faith.

>Based on the existing qualitative research, the negative effects of spiritual abuse can be very serious. Ward (2011) found evidence of persistent physical illness in multiple respondents, including major surgery, chronic hospital visits, gallstones, biliary colic of the liver, and inflamed esophagus, understood to be a result of stress-induced exhaustion from spending time in spiritually abusive environments. Swindle (2017) found that all seven of her participants reported some level of emotional trauma; psychological consequences included depression, anger, fear, feeling stuck, confusion, and decreased self-worth. One participant was shunned and banned from all church group activities when it was discovered that she was being treated with depression medication and seeing a psychiatrist (Swindle 2017). Many of the respondents in a survey by Oakley & Kinmond (2014) reported leaders who demanded complete, unquestioning obedience; a consensus that a leader is divinely appointed to that position can leave abusers unchallenged. Abuse by religious figures appears to be quite destructive. Stevens et al. (2019) found that college students who alleged sexual abuse by religious figures were just as symptomatic as those abused by their parents. It can be inferred from this finding that religious leaders have a strong, near-parent-level potential for abusive harm, but more research is needed to support this inference. 

>There are also concerns related to secondary trauma for clinicians working with R/S abused clients. In a small study of five counselors who had worked with spiritually abused clients, Gubi & Jacobs (2009) found symptoms of secondary traumatic stress disorder and visceral traumatization, including anger, sadness, outrage, grief, cynicism, and helplessness. Encouragingly, working with these clients also profoundly deepened the counselor’s relationship with God (Gubi & Jacobs 2009). Increasing visibility and training around R/S abuse may lead to protections and benefits not only for survivors but practitioners as well.

>However defined, trauma occurring in a R/S setting has the effect of reducing a victim’s ability to use R/S as a coping strategy, at least for those who exercise their R/S in organized contexts (Panchuk, 2018). This may be the result of religious leaders explicitly claiming to represent God (Ward, 2011) or simply of the abuse occurring in a religious context and therefore carrying traumatic connotations for the survivor. Given the broad evidential support for the role of R/S in healing from trauma, it is especially pernicious that R/S abuse takes place in religious settings of such strong potential for growth and healing. 

In light of these concerns, a valid scale of spiritual harm and abuse is needed. Such a scale may provide myriad potential benefits. Practitioners of clients whom they suspect may have been the victims of R/S abuse could administer the scale as part of their intake process, enabling them to quickly check their client’s score against established, valid, and reliable norms. A reliable measurement of exposure to potential spiritual abuse and its effects can also be used extensively for research purposes, looking for relationships between spiritual abuse and any number of other psychological, health, or other measures.  Their research question was: “Which types of R/S abuse most succinctly capture the phenomenon of being broadly exposed to R/S abuse?” The hypothesis is that factor analysis will reveal <30 items that can reliably comprise a shorter scale for broad exposure to religious and spiritual abuse and its common effects.

To date only one scale has been developed to measure religious or spiritual abuse @Keller2016 and this scale has not been used in any subsequent peer-reviewed research. Other scales measure various types of abuse, but not R/S abuse specifically. The Cumulative Trauma Scale (Kira, et al. 2008) was developed to measure overall trauma amongst a Middle Eastern refugee population. The Child Abuse and Trauma Scale (Sanders & Becker-Lausen, 1995) measures childhood and adolescent experiences. The Trauma History Screen (Carlson, et al. 2011) includes a handful of items that could be religion-related, like sexual abuse or being “suddenly abandoned by a spouse, partner, parent, or family” but does not ask about the cause of the abandonment. The Trauma Symptom Checklist (Briere & Runtz, 1989) measures a respondent’s current trauma levels and contains helpful subsets of trauma, but no items ask specifically about anything religious. Other trauma-related screens and scales similarly lack any specific religious component.

@KochEdstrom2022 laid the foundation for a scale measuring exposure to potentially spiritually abusive experiences. They defined the construct of spiritual harm and abuse and developed an initial item pool. They conducted EFA which revealed a handful of factors which they used to reduce the number of items and to define several subscales.

This paper extends on @KochEdstrom by using additional psychometric evidence to gather additional evidence of validity for the nascent Spiritual Harm & Abuse Scale (SHAS). The goal of the current study was to refine the  an outcome measure that reflects a patient’s exposure to and damage from spiritual harm and abuse. We aimed to establish an item bank on healthcare engagement that is sufficiently unidimensional to yield a single score, is free from differential item functioning based on race, gender, or chronic condition, and maximizes parsimony and precision across the continuum of the latent construct.
