# Content Validity
In this chapter, we consider the content validity of the Spiritual Harm and Abuse Scale (SHAS). We begin by defining content validity and discussing its importance. Then we document the work we did to map the domain of spiritual abuse for the purpose of developing items for piloting and operational use. We conclude by considering what scope exists for more work in this area that would improve future development of SHAS instrumentation.

## About Content Validity
The focus of content validity is "the relationship between the content of a test and the construct it is intended to measure" [@Standards]. The overarching question is what is the domain of content from which to design blueprints for forms and items?

## Content Specification
"Test developers often work from a specification of the content domain. The content specification carefully describes the content in detail, often with a classification of areas of content and types of items. " [@Standards]. For the purpose of piloting items, the domain of spiritual abuse included two constructs: external (abusive) events and internal states (of emotional harm).

### External Events
One domain of spiritual abuse is external abuse _events_. The focus is on something that happened, or a pattern of recurring behavior on the part of someone in a place of spiritual authority that was experienced by the examinee as abusive. The first 52 items of the SHAS were drawn from this domain of possible abusive events. To each item, an examinee was offered five response categories:

1. Never
2. Once or twice
3. Sometimes
4. Often
5. Always

To sum each examinee's vector of responses to these items is to accumulate evidence of abuse. In the aggregate, scores for this collection of items could range from 52 to 260. An examinee who _never_ experienced _any_ of these events would score 52. At the other extreme, an examinee who scored 260 had _always_ experienced _all_ of these events.

### Internal States
Another important domain of spiritual abuse is _internal states_. The focus is on the subjective experience of an examinee "as a result of negative experiences in church or Christian group settings." The questionnaire included 14 items asking examinees about their emotions in response to events. To each item, an examinee was offered the same five response categories as before:

1. Never
2. Once or twice
3. Sometimes
4. Often
5. Always

To sum each examinee's vector of responses to these items is to accumulate evidence of internal emotional _harm_. Total scores for these items could range from 14 to 70. Examinees who _never_ experienced _any_ of these unpleasant emotions would score 14, while examinees who scored 70 had _always_ experienced _all_ of the difficult emotions.

### Additional Domains

@ReiseWaller2009 make some interesting points about the nature of the traits addressed in clinical settings which provoke thought about the trait of spiritual abuse.

## Summary
What counts as spiritual abuse? What counts as evidence of it?
