# Methods

## Item Pool Development

We developed a Spiritual Harm and Abuse item pool. We previously validated the spiritual harm and abuse construct using a literature review, expert reviews, and qualitative concept elicitation interviews with people.

The item pool for this study (66 items) was generated by mapping items from publicly available measures of similar constructs and writing new items to achieve construct coverage. 

>All items were written or edited to a 6th grade reading level. Cognitive interviews with 56 patients included think aloud responses, prompts for comprehension, retrieval, judgement or other difficulties responding to items, and relevance [22]. The a priori standard for item inclusion was three consecutive interviews establishing comprehension, relevance, and no difficulties. Minor wording changes were based on consensus of study interviewers and the principal investigator, major wording changes were addressed in dedicated item review meetings of the study staff, investigators, and consulting primary care or mental health providers.

## Participants and Procedures

>We conducted an online survey of listeners to progressive Christian podcasts. Our sampling priorities for this initial quantitative validation were (a) variability across the full range of the construct; and (b) representation of diverse clinical samples from target populations for the measure’s use [23]. The sampling frame was identified from administrative data in the VA Corporate Data Warehouse [24]. We sampled from the VA primary care population, who are predominantly male, and older, with poorer health status, and less racially diverse as compared to other healthcare populations [25]. Inclusion criteria were: veteran, aged 18–80, White or Black race (Asian, Pacific Islander, and Native Americans are each≤1% of users and accuracy in public sector administrative data is poor [26]), a valid mailing address in the medical record, at least one past-year primary care visit to the assigned primary care panel, and a diagnosis of one of four prevalent chronic conditions (diabetes, hypertension, depression, PTSD), as indicated by one inpatient stay or two outpatient visits on different dates of service. Exclusion criteria were active diagnoses of dementia or psychotic disorders, or 90-day risk for hospitalization or death in the top 5% as indicated by the VA’s Care Assessment Needs score [27]. Stratified sampling was used to ensure sufficient cell size for subgroup comparisons and DIF analyses. Sampling was stratified by chronic condition cohort, and within cohorts to oversample Women, Black veterans and Hispanic veterans. Cohorts were also balanced on health status, as indicated by risk adjustment scores [28]. Participants were consented before beginning the survey. The IRB at Northwest University. The data were collected from January 28, 2021 to February 27, 2021.

However, the data come from a convenience sample which raises some challenge of sampling bias. Dan sent the link out to [lots of people], and (if memory serves) encouraged them to send it to people _they_ knew. This would seem to bias responses toward people demographically similar to Dan: white, Millennial, west coast American, middle class, highly educated, primarily Protestant and Catholic Christian, etc. This will be more apparent upon closer inspection of the demographics of the sample.

One source of examinees was people who listen to progressive Christians podcasts such as  _You Have Permission_ which Dan produced at the time of data collection. This is a known source of bias toward people who have some interest in Christianity along with at least some level of rejection of conservative/orthodox Christianity and/or political conservatism. However, this would be an appropriate group from which to invite participation if the target population is people who have experienced spiritual abuse.

Sample Characteristics

Table about here.

## Measures

**Spiritual Harm and Abuse items**

Koch tested 66 candidate items representing the two domains of the spiritual harm and abuse construct: external events (52 items) and internal states (14 items). The measure asks respondents to frequency with which they experienced each event or state. Candidate items were provisionally scored on a 5-point Likert-type scale, with response options of “Never,” “Once or twice,” “Sometimes,” “Often,” and “All the time.”


## Data Analysis

>Our analysis strategy was to pare down the item pool to reflect the latent construct of healthcare engagement. Although our theoretical model was composed of four inter-related domains of engagement behaviors, engagement was hypothesized to stem from generalized self-efficacy across these behaviors [16], making the common variance across domains our primary interest, rather than comprehensive coverage of each domain that would result in separate scales or subscales. We assumed an effect-indicator model from the beginning of the analysis [32], and therefore, the analysis strategy also targeted removal of smaller, extraneous factors in an effort to identify a sufficiently unidimensional set of items that could form a single scale. A different set of theoretical assumptions, such as creating an inventory of knowledge and skills, could be consistent with a causal-indicator model, where the focus of item selection would be to maximize the unique content represented by each subdomain [33]. While there are merits of each approach, we felt the latter would have contributed to proliferation of similar constructs in the field, overemphasized each subdomain’s independence, increased respondent burden, and would have had relatively limited utility in healthcare systems due to the need to reliably assess and interpret multiple domains and scores.

>Preliminary analyses examined classical item-level statistics, polychoric correlations, and hierarchical cluster analysis [34] to identify poorly functioning items. Next, we conducted iterative exploratory bifactor analyses using the psych package in R. We started by selecting four subfactors corresponding to the four hypothesized domains of the construct but considered solutions with three subfactors as well. (For a detailed illustration of how to apply bifactor modeling to patient experience data, see Reise et al. [35]) We evaluated dimensionality based on general factor saturation and computed Omega-Hierarchical (Omega-H), where values > 0.70 suggest sufficient unidimensionality for IRT modeling [36]. In addition, we calculated explained common variance (ECV), the relative strength of a general factor compared to group factors, targeting ECV values > 0.60 as a tentative benchmark [36].

>As a final step, we used a statistical learning theory (SLT) approach to optimize the parsimony of the item pool, minimize expected prediction error, and incorporate criterion validity into the item selection process [37]. SLT methods have good potential to inform the development of latent trait scales. The measurement of complex constructs, such as patient engagement, requires investigators to balance the theoretical and conceptual basis of the construct with empirical results in making judgments in the presence of structural ambiguity [38]. Well-documented pitfalls are associated with too great an emphasis on optimizing inter-item correlations, such as the proliferation of reliable but narrow scales or subscales that under-represent a construct [39].

>In our context, the SLT procedure helped us to identify items that could be deleted because they were not sufficiently related to criterion variables. We derived a cross-validated set of items that correlated with the validity indicators for each of the three domains of the model using the Best Items Scale that is Cross Validated, Unit-weighted, Informative, and Transparent (BISCUIT), which has been shown to produce parsimonious models with comparable levels of predictive accuracy, even at high levels of missing data when compared to other statistical learning techniques [40]. The tuning parameter was selected to exert a moderate degree of influence on item selection, identifying the best 20 items for each criterion, with 1000 bootstrap replications. All items that appeared in optimal scales for all three validity indicators in > 1 replication were retained in the item pool.

>To illustrate the structure of our final set of items prior to IRT analyses, we ran a confirmatory bifactor model corresponding to the final structure determined by exploratory factor analyses. For this final model, we report Omega-H, ECV, Comparative Fit Index (CFI), the Tucker Lewis Index (TLI), and the root-mean-square error of approximation (RMSEA). Next, we estimated IRT parameters using the graded response model (GRM) [41], as well as the corresponding IRT-based bifactor model with three subfactors [42]. We did this with the understanding that unidimensional parameters might still be distorted by subfactors evident in a bifactor model. Therefore, we applied a procedure to convert conditional general factor slopes into marginal slopes, using formulas 10 and 11 provided in a didactic article by Toland et al. [43], citing detailed work on these procedures [44]. Once in marginal form, the slopes and location parameters from the bifactor model can be fairly compared to unidimensional models, and may be scored “as if” they were from unidimensional models.

>Differential item functioning (DIF) analysis compared race (Black/African-American vs. White), age (65 and above vs below 65), mental health vs physical health cohorts, and financial strain. We applied logistic ordinal regression with IRT scoring, commonly used in the development of PROMIS instruments [45]. We used the Chi-squared likelihood-ratio statistic as the initial DIF detection criteria (alpha < 0.01), and a cut-off of McFadden pseudo R2Δ ≥ 0.02 in model comparisons to determine substantial DIF, a reasonable threshold used in the development of self-reported health outcomes [46].

All analyses were conducted in **R**, using the **psych** package [47] and **lavaan** [48] for factor analyses, **mirt** [49]for IRT analyses and **lordif** [45] for DIF analyses.