# Data Collection

The data were collected online from January 28, 2021 to February 27, 2021.

A final total of 3,222 people responded to the survey at some level. Depending on how much data are missing, this is an impressively large sample size which will provide lots of power for most simple statistics and should for the most part satisfy the large-sample requirements of the advanced statistical procedures associated with measurement work (i.e., factor analysis, IRT).

However, the data come from a convenience sample which raises some challenge of sampling bias. Dan sent the link out to [lots of people], and (if memory serves) encouraged them to send it to people _they_ knew. This would seem to bias responses toward people demographically similar to Dan: white, west coast American, middle class, highly educated, primarily Protestant and Catholic Christian, etc. This will be more apparent upon closer inspection of the demographics of the sample.

One source of examinees was people who listen to progressive Christians podcasts such as  _You Have Permission_ which Dan produced at the time of data collection. This is a known source of bias toward people who have some interest in Christianity along with at least some level of rejection of conservative/orthodox Christianity and/or political conservatism. However, this would be an appropriate group from which to invite participation if the target population is people who have experienced spiritual abuse.