# Discussion

The purpose of this study was to further validate and enhance the Spiritual Harm and Abuse Scale (SHAS) with the use of the Rasch Rating Scale model. The present study improves upon the sample dependency of factor analysis results and contributes new understanding about the psychometric characteristics of the SHAS.

In this study, we specifically examined unidimensionality, Rasch person/item separation
reliability, model-data fit, distribution of the variable map based on the locations
of persons and items, and individual item qualities of the SHAS. In terms of dimensionality, we found the SHAS to be essentially unidimensional. We also found the SHAS highly reliable from the view of Rasch person/item separation reliability, indicating that most of the items are sensitive enough to capture different levels of spiritual abuse, and most persons' observed values overlap with the expected values. Similarly, there was a close correspondence between the data and the Rasch Rating Scale model except for the outliers in the XXX ends of the continuum, indicating a reasonable model-data fit. Regarding the variable map, our results indicate that the SHAS, overall, captures a range of item severities that reflect the order structure of spiritual abuse. However, we also found that [items related to the use of mathematics in daily life are quite difficult for students to agree with,] and [there is a shortage of items at the very high and low ends of the continuum across the four factors]. The SHAS can capture people who have experienced moderate severity of spiritual abuse, but it is not sensitive enough to discriminate among people who have experienced very severe and less severe spiritual abuse. [For example, based on our Rasch Rating scale model analysis, someone with a measure of − 3.00 logits and another with a measure of − 2.00 logits would be more likely to respond to the SHAS in the same way because there is no item on the scale that targets very low levels of spiritual abuse. Hence, we would not be able to detect which person has relatively more or less spiritual abuse in comparison to each other. It would be similarly impossible to distinguish levels of spiritual abuse between a person with a measure of 3.00 logits and another with a measure of 2.00 logits, and decide who has experienced more severe spiritual abuse due to lack of items at the high end of the continuum.]

Finally, in terms of item quality, XX of the XX items exhibited good psychometric quality, whereas XX items were misfits. XXX items were redundant because they provided the exact same information with identical pairs of each item, displaying the same contributions to the sensitivity of the SHAS. Hence, they can be removed from the scale to shorten the duration of administration.

Use of the Rasch measurement model in our study provided a more powerful analysis of the functioning of the SHAS at the item level and offered in-depth insights on applicability of the scale in wider contexts due to its sample independent nature. Whereas factor analytic approaches such as exploratory factor analysis and confirmatory factor analysis do not provide invariant measurement due to their sample dependency, the Rasch measurement model is independent from the items that form the scale and independent from the sample that the scale is administered to. This feature will increase the applicability of the scale in wider contexts and replicability of the present study in different populations due to the possibility of direct application of the standards developed in one study to data administered in another study (Yan and Mok 2012).

In conclusion, the results of this study provide strong evidence for the validation of the SHAS despite the need for considering the deletion of XX items that are misfits and of XX items that are redundant. The revision or development of new items can also be considered to capture gradations of challenges at the very high and low ends of the continuum to detect people with very high and low levels of spiritual abuse.

##Implications and future directions

This study presents the validation of the SHAS using the Rasch measurement model, for assessing spiritual abuse in adults. The findings have important implications for clinicians and researchers who are concerned about spiritual abuse. 

Moreover, the finding that the majority of the SHAS items were of high quality implies that the items provide adequate information to measure moderate levels of spiritual abuse. However, we found the SHAS less able to distinguish people with very high and low levels of spiritual abuse. Hence, for now clinicians and researchers should be cautious when interpreting their results for people who have very high and low spiritual abuse levels.

In addition to the SHAS scale being a self-report scale, limitations associated with this study include the grade level. Because this study consists of responses of students from one grade level (i.e., 8th grade), the results might not be generalizable to students in other grades.

There are a few suggestions for future studies. First, future research should consider eliminating the 11 items that either demonstrated misfit or were redundant, and include only the remaining 34 items that have good item qualities. Second, there is a need for the revision or development of new items to capture students with very high and low levels of spiritual abuse. Third, permanent changes to the SHAS need to be made after conducting pilot studies with other 8th grade samples. Fourth, in terms of generalizability of the findings, this study should be replicated by future studies with the Rasch measurement model analysis on samples of 6th and 7th grade students, and of high school students.

> The results supported the hypothesis that fewer than 30 items across fewer than 10 factors would be found to comprise a spiritual abuse scale with adequate reliability. In the end, 27 items over 6 factors were found to comprise the new Spiritual Harm & Abuse Scale: 
- Maintaining the System
- Internal Distress
- Embracing Violence
- Controlling Leadership
- Harmful God-image
- Gender Discrimination

>The resulting scale can be used in clinical settings to quickly check a client’s exposure to spiritual abuse and possible resulting consequences. It can be administered in roughly the same amount of time as short measures like the Beck Anxiety Inventory.

> The results of this research will comprise a scale and clinical screener for use by clinicians, potentially providing myriad benefits. Practitioners with clients whom they suspect may have been the victims of R/S abuse could administer the scale as part of their intake process, quickly able to check their client’s score against established, valid, and reliable norms.

>*Limitations and Future Research*. One limitation of the SHAS is that it was developed on a largely white and Protestant/former Protestant population. It is possible that major types or subthemes of spiritual abuse not captured here are more prominent in Catholic or non-white Christian settings, especially given that R/S can be such central forces in many of those groups. This would be a fruitful area of future study. Research looking at spiritual abuse among the LGBTQ+ community might also yield insights specific to that population. Future research could also distinguish normed scores of this scale for different populations and denominations.

>Much additional analysis could also be done on the prevalence data contained in the survey responses. Comparisons could be made to the other existing Western quantitative spiritual abuse survey (Oakley & Kinmond, 2014). Future research can look for correlations between exposure to R/S abuse and other religion-related measures, for example, the Religious Involvement Scale (Piedmont, et al. 2009), the Penn Inventory of Scrupulosity (Abrahamowitz et al, 2002), the Death Anxiety Scale (Templer, 1970), the Hell Anxiety Scale (Cranney, et al. 2017), and others. Comparisons can also be made with other trauma-related scales, like the Child Abuse and Trauma Scale, the Trauma History Screen, and the Cumulative Trauma Scale. Validity can also be established for both this new scale and the Spiritual Abuse Questionnaire (Keller, 2016) by correlating the two. 

>The final screener has the potential to both improve therapy for innumerable clients who have experienced negative religious experiences and to contribute a knowledge base for any future clinical training around working with spiritually abused clients. The scale may also contribute to future research that could be critical in understanding not only the mechanisms and experience of spiritual abuse but also perhaps the enduring power of religion, both to heal and to harm.