## Classical Item Analysis

```{r}
# LOAD DATA
all <- read.csv("data/all.csv")
source("code/ApplyAllLabels.R")
```


```{r describe}
# DESCRIBE DATA
library(kableExtra)
items.tbl <- as.data.frame(psych::describe(all[,1:66]))
items.tbl <- subset(items.tbl, select = -c(vars, trimmed, median, mad, min, max, range))

round(items.tbl,2) %>%
  kbl(align = "ccccccccccccc", caption = 'Classical Item Statistics') %>%
  kable_styling(bootstrap_options = "condensed", font_size = 14, fixed_thead = T)

# A POSSIBLE BAR PLOT OF ITEM STATISTICS
# barplot(item_stats$nbr.val, main="Complete Cases", horiz=TRUE, col='red')
# barplot(item_stats$nbr.val, main="Complete Cases", horiz=FALSE, col='red', ylim = c(0,8000),names.arg=labs)

```


```{r ext-pbis}
# DESCRIPTIVES
library(ltm)
i <- ltm::descript(all[,1:66])
items.tbl2 <- as.data.frame(i[["perc"]]) # extract category response frequencies
names(items.tbl2) <- c('1' = "Never", '2' = "Once or twice", '3' = "Sometimes", '4' = "Often", '5' = "All the time")
items.tbl2 %>%
  kbl(digits=2, align = "ccccc", caption = 'Category Frequencies') %>%
  kable_styling(bootstrap_options = "condensed", font_size = 14, fixed_thead = T)

# library(formattable)
# formattable(items.tbl2, align = "ccccc", digits = 2, list(area(col = 1:5) ~ color_tile("transparent", "blue")))
```

```{r item-analysis}
# CLASSICAL ITEM ANALYSIS
# library(CTT)
# CTT::itemAnalysis(all[,1:66], itemReport=TRUE, NA.Delete=TRUE, rBisML=FALSE, easyFlag, pBisFlag, bisFlag, flagStyle = c("X",""))
# CTT::itemAnalysis(all[,1:66], itemReport=TRUE, NA.Delete=TRUE, rBisML=FALSE, flagStyle = c("X",""))
```

```{r}
# MORE ITEM STATISTICS
library(pastecs)
item_stats <- pastecs::stat.desc(items.tbl) # use the stat.desc() to render data frame of item stats
item_stats
item_stats <- t(item_stats) # transpose the data frame
item_stats <- data.frame(item_stats)
item_stats[order(item_stats$mean), ] # order by mean
item_stats[order(item_stats$nbr.val), ] # order by N cases
```

**Item-Total Correlations**.
```{r pbis, fig.cap='Item-Total Correlations'}

# POINT BISERIAL CORRELATIONS
# ltm::biserial.cor(x, y, use = c("all.obs", "complete.obs"), level = 1)

```

**Distractor Analysis**.
```{r distractor}
# DISTRACTOR ANALYSIS
# CTT::distractorAnalysis
```

**Outlier Analysis**.
```{r outliers}
# OUTLIERS
# psych::outlier(items)
```

**Skew and Kurtosis**.