project:
  type: book

book:
  title: "Validation of the Spiritual Harm and Abuse Scale with the Rating Scale Model"
  author:
    - Jack Huber, Swedish Medical Center
    - Dan Koch, Northwest University
  date: "8/13/2022"
  chapters:
    - index.qmd
    - intro.qmd
    - methods.qmd
    - results.qmd
    - discussion.qmd
    - references.qmd
  downloads: [pdf, epub]
  page-navigation: true
  navbar: 
    background: primary
  site-url: https://jackhuber.org/SHAS

bibliography: [references.bib, packages.bib]

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreport
    keep-tex: true

editor: visual

