--- 
title: "Validity Evidence for the Spiritual Harm and Abuse Scale (SHAS)"
author:
  - Jack Huber, Swedish Medical Center
  - Dan Koch, Northwest University
date: "`r format(Sys.time(), '%B %Y')`"
site: bookdown::bookdown_site
documentclass: report
bibliography: [book.bib, packages.bib]
url: https://jackhuber.org/SHAS/
description: |
  This is a minimal example of using the bookdown package to write a book.
  The HTML output format for this example is bookdown::gitbook,
  set in the _output.yml file.
link-citations: yes
github-repo: https://github.com/jackbhuber/SHAS.git
---
# About this Project
This is a reproducible research project for validation of the nascent Spiritual Harm and Abuse Scale (SHAS), developed by Dan Koch. It aims to function as an evolving technical report to conceptualize and document various validity studies -- and, by extension, validity evidence -- for this scale. We hope some of these validity considerations and empirical studies amount to meaningful publishable contributions to the nascent research literature in spiritual abuse and/or the literature in religion, counseling psychology, and/or psychological measurement.

The project is open source, for collaboration. It is built in R using the R Studio IDE [@R-base]. No Excel, no SPSS, no Word. It is built in `bookdown` (@R-bookdown) and hosted at Github as a public repository at https://github.com/jackbhuber/SHAS. There it is served over Github Pages as a website -- https://jackhuber.org/SHAS/ -- for collaboration between Jack and Dan.

## Research Questions

Validation is research into the meanings and uses of scores from instruments. It can be an ongoing research agenda. Following is an initial set of questions to guide research and scale improvement of the SHAS:

* **Item analysis and refinement** - Do some items have too many response categories?
* **Data reduction** - As written and executed, which items appear to be critical (best performing) and which appear to be redundant or noisy? What might a shorter, streamlined instrument look like?
* **Person fit** - How well does the current scale fit the population of examinees? Are there ceiling or floor effects? To what extent might the existing items under-represent the full range of abuse?
* **Scale invariance** - Do the scales mean the same thing to different groups of examinees? To what extent do these scales (abuse constructs) vary by age, gender, and/or sexuality?
* **Developmental pathway** - Beyond the current conceptualization of scales composed of redundant items, what might an incremental scale of abuse with diagnostic items look like?

```{r, include=FALSE}

knitr::opts_chunk$set(comment = "", warning = FALSE, message = FALSE, tidy.opts=list(width.cutoff=60), tidy = TRUE)

knitr::opts_knit$set(verbose = FALSE)

# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'ltm','knitr', 'psych', 'rmarkdown', 'VIM'
), 'packages.bib')
```

